### ISSUE TITLE
has no attribute 'VisSurfTriangle'

### ISSUE THREAD

**Issue by asdasdqwdqwfsdf** [orbingol/geomdl-examples#7]
Hi!

how to fix the error:

Traceback (most recent call last):
  File "C:/Users/python/geomdl-examples/surface/ex_torus.py", line 44, in <module>
    vis_comp = VisMPL.VisSurfTriangle(vis_config)
AttributeError: module 'geomdl.visualization.VisMPL' has no attribute 'VisSurfTriangle'

**Comment by orbingol** [comment]
You can use `VisMPL.VisSurface`. It is a direct replacement for `VisSurfTriangle`.
