### ISSUE TITLE
In example isu, there is no data directory

### ISSUE THREAD

**Issue by yuanmluo** [orbingol/geomdl-examples#8]
Hello. Fantastic work!
Could you please send me the data file? I am working on the valve parametric design and thinking switch to the tool provide here. Could you provide the data file? I understand the work comes from the ISU, but could you at least provide source link to download?

Thanks!

**Comment by orbingol** [comment]
Unfortunately, it is impossible for me provide the data files. I can help with using the API if you can obtain the data files.
