### ISSUE TITLE
The VisVolume() function is not working

### ISSUE THREAD

**Issue by Arka24** [orbingol/geomdl-examples#9]
This is an issue related to the volume examples. Is it possible to generate a solid volume using a NURBS volume object and Visvolume()? All the volume examples in this repo have defined the bounding surfaces and then created a volume. I tried to create a cuboid using the NURBS volume object however, the render function is plotting the evaluation points instead of the solid.  How to get a proper 3D visualization of the solid?

This is the pdf form of my notebook.
[NURBS_Solid.pdf](https://github.com/orbingol/geomdl-examples/files/5470853/NURBS_Solid.pdf)

**Comment by orbingol** [comment]
`VisVolume` is intended to render the points as it is the fastest way to render it. There is also a `VisVoxel` class which renders the voxels. There are some glitches in rendering the voxels, it is not perfect but representative. There is also possibility to extract the isosurface and render it, if you mean this by saying proper 3D visualization of the solid.

Please take a look at this example for more details on the methods available other than `VisVolume`:

https://github.com/orbingol/geomdl-examples/blob/master/volume/ex_planar_bspline.py

**Comment by Arka24** [comment]
Thanks for your response. I wanted to have a visualization similar to the CAD packages, with shaded edges and surfaces. I will try out the alternatives that you suggested. Just a follow up question, is it possible to export the NURBS volume object to a CAD readable format such as ".IGES" or ".stp" for better visualization?

**Comment by orbingol** [comment]
I am not sure whether IGES supports NURBS volumes or not. I guess it is only curves and surfaces. I haven't found precise references but I am guessing STEP also supports curves and surfaces only. Rhino supports an object named "Cage" which looks like NURBS volumes, but somehow it didn't work with OpenNURBS -- I don't remember why.

I've published another tool, [rw3dm](https://github.com/orbingol/rw3dm) which can convert most geomdl objects into OpenNURBS/Rhino format.
